name: Extend PD Link

on:
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *'

jobs:
  view-links:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Puppeteer
        run: |
          npm install puppeteer cheerio axios

      - name: Read and View PixelDrain Links
        run: |
         node script.js

      - name: Send Report to Telegram
        run: |
          TOKEN="${{ secrets.TELEGRAM_BOT_TOKEN }}"
          CHAT_ID="${{ secrets.TELEGRAM_CHAT_ID }}"
          MESSAGE=$(cat report.txt)
          curl -s -X POST "https://api.telegram.org/bot$TOKEN/sendMessage" -d "chat_id=$CHAT_ID&text=$MESSAGE" -d "parse_mode=Markdown"
