name: Extend PD Link

on:
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *'

jobs:
  view-links:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Puppeteer
        run: |
          npm install puppeteer cheerio axios

      - name: Read and View PixelDrain Links
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: node script.js

      - name: Fetch files
        run: |
          # Make the curl request using the secret API key and capture the output
          response=$(curl -X GET -u :${{ secrets.PD_API }} https://pixeldrain.com/api/user/files)
          
          # Parse the JSON response to extract file IDs and create links
          echo "$response" | jq -r '.files[] | "https://pixeldrain.com/u/\(.id)"' > links.txt

      - name: Commit links.txt
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add links.txt
          git commit -m "Update links.txt" || echo "No changes to commit"
          git push
