name: Download TikTok and Send to Telegram

on:
  workflow_dispatch:
  schedule:
    - cron: '0 17 * * *'  # Menjalankan setiap hari pada pukul 17:00 UTC

jobs:
  download-and-send:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install Dependencies
      run: |
        sudo apt-get install -y yt-dlp  # Menggunakan yt-dlp untuk mengunduh video
        sudo apt-get install -y nload #Menginstall nload untuk memonitor bandwidth

    - name: Monitor Bandwidth Before Download
      id: start_bandwidth
      run: |
        nload -t 1 -o /tmp/bandwidth.log &
        sleep 5

    - name: Download TikTok Video
      env:
        TIKTOK_URL: 'https://www.tiktok.com/@user/video/7458204807241731335'  # Ganti dengan URL TikTok
      run: |
        yt-dlp -v -o '/tmp/video.mp4' "$TIKTOK_URL"

    - name: Monitor Bandwidth After Download
      run: |
        kill $(jobs -p)  # Menghentikan proses nload
        echo "Bandwidth Usage:" >> /tmp/bandwidth.log
        cat /tmp/bandwidth.log >> /tmp/bandwidth_usage.txt

    - name: Send Video to Telegram
      env:
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
      run: |
        curl -X POST "https://api.telegram.org/bot$TELEGRAM_BOT_TOKEN/sendVideo" -F chat_id=$TELEGRAM_CHAT_ID -F video=@/tmp/video.mp4

    - name: Commit Bandwidth Usage to Repository
      run: |
        git config --local user.name "github-actions"
        git config --local user.email "action@github.com"
        mv /tmp/bandwidth_usage.txt ./bandwidth_usage.txt
        git add bandwidth_usage.txt
        git commit -m "Add bandwidth usage report"
        git push
