name: Download TikTok and Send to Telegram

on:
  workflow_dispatch:
  schedule:
    - cron: '0 17 * * *'  # Runs daily at 17:00 UTC

permissions:
  contents: write

jobs:
  download-and-send:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y yt-dlp

    - name: Save Cookies to File
      env:
        TT_COOKIES: ${{ secrets.TT_COOKIES }}
      run: |
        echo "$TT_COOKIES" > cookies.txt

    - name: Download TikTok Video
      env:
        TIKTOK_URL: 'https://www.tiktok.com/@user/video/7458204807241731335'
      run: |
        yt-dlp -v --cookies cookies.txt -o '/tmp/video.mp4' "$TIKTOK_URL"

    - name: Capture Bandwidth Usage with ifconfig
      run: |
       # Replace eth0 with your network interface name
       RX=$(ifconfig eth0 | grep 'RX packets' | awk '{print $5}')  # Received bytes
       TX=$(ifconfig eth0 | grep 'TX packets' | awk '{print $5}')  # Transmitted bytes

       # Convert bytes to MB
       RX_MB=$(echo "$RX / 1048576" | bc)
       TX_MB=$(echo "$TX / 1048576" | bc)

       # Log the usage
       echo "Bandwidth Usage All Time:" > /tmp/bandwidth_usage.txt
       echo "  Received: $RX_MB MB" >> /tmp/bandwidth_usage.txt
       echo "  Transmitted: $TX_MB MB" >> /tmp/bandwidth_usage.txt

       # Display the log
       cat /tmp/bandwidth_usage.txt

    - name: Send Video to Telegram
      env:
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
      run: |
        curl -X POST "https://api.telegram.org/bot$TELEGRAM_BOT_TOKEN/sendVideo" \
        -F chat_id=$TELEGRAM_CHAT_ID -F video=@/tmp/video.mp4

    - name: Commit Bandwidth Usage to Repository
      run: |
        git config --local user.name "github-actions"
        git config --local user.email "action@github.com"
        mv /tmp/bandwidth_usage.txt ./bandwidth_usage.txt
        git add bandwidth_usage.txt
        git commit -m "Add bandwidth usage report"
        git push "https://${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git"
