name: TikTok Downloader

on:
  workflow_dispatch: # Jalankan manual
  schedule:
    - cron: "0 12 * * *" # Jadwal (Setiap hari pukul 12:00 UTC)

jobs:
  download_tiktok:
    runs-on: ubuntu-latest

    steps:
      # Langkah 1: Checkout repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Langkah 2: Setup Python
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      # Langkah 3: Install dependencies
      - name: Install Dependencies
        run: |
          pip install requests yt-dlp
          sudo apt-get update
          sudo apt-get install -y rclone
          
      - name: Set Telegram Secrets and Cookies
        run: |
          echo "${{ secrets.TT_COOKIES }}" > cookies.txt
        env:
          TT_COOKIES: ${{ secrets.TT_COOKIES }}      
          
      # Langkah 4: Jalankan script Python
      - name: Run TikTok Downloader
        env:
          VIDEO_DIR: './videos'
          ARCHIVE_FILE: './archive.txt'
          LOG_FILE: './download.log'
          NOTIF_CHANNEL_ID: '-1002471139847'  # Ganti dengan ID channel notifikasi
          VIDEO_CHANNEL_ID: '-1002357695125'  # Ganti dengan ID channel video
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}  # Token bot Telegram (gunakan GitHub Secrets)
          TT_COOKIES: ${{ secrets.TT_COOKIES }}  # Cookies TikTok (gunakan GitHub Secrets)
        run: |
          python main.py
