name: TikTok Downloader

on:
  workflow_dispatch: # Jalankan manual
  schedule:
    - cron: "0 12 * * *" # Jadwal (Setiap hari pukul 12:00 UTC)

jobs:
  download_tiktok:
    runs-on: ubuntu-latest

    steps:
      # Langkah 1: Checkout repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Langkah 2: Setup Python
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      # Langkah 3: Install dependencies
      - name: Install Dependencies
        run: |
          pip install requests yt-dlp
          sudo apt-get update
          sudo apt-get install -y rclone
          
      - name: Set Telegram Secrets and Cookies
        run: |
          echo "${{ secrets.TT_COOKIES }}" > cookies.txt
        env:
          TT_COOKIES: ${{ secrets.TT_COOKIES }}      

      - name: Load Rclone Config from Secret
        run: |
          echo "$RCLONE_CONF_BASE64" | base64 --decode > rclone.conf
        env:
          RCLONE_CONF_BASE64: ${{ secrets.RCLONE_CONF_BASE64 }}
          
      # Langkah 4: Jalankan script Python
      - name: Run TikTok Downloader
        env:
          VIDEO_DIR: ${{ github.workspace }}/VIDEO/ACPN
          ARCHIVE_FILE: ${{ github.workspace }}/acpn.txt
          LOG_FILE: ${{ github.workspace }}/download.log
          NOTIF_CHANNEL_ID: '-1002471139847'  # Ganti dengan ID channel notifikasi
          VIDEO_CHANNEL_ID: '-1002357695125'  # Ganti dengan ID channel video
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}  # Token bot Telegram (gunakan GitHub Secrets)
          TT_COOKIES: ${{ secrets.TT_COOKIES }}  # Cookies TikTok (gunakan GitHub Secrets)
        run: |
          mkdir -p $VIDEO_DIR
          touch $ARCHIVE_FILE
          touch $LOG_FILE
          python main.py

      - name: Push Acpn
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git pull origin main
          git add acpn.txt
          git commit -m 'Update acpn.txt after TikTok uploads'
          git push origin main

